matrix:
  include:
    - stage: Lint
      language: node_js
      os: linux
      node_js: '10'
      script: >-
        cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: Build
      os: linux
      language: android
      env:
        - BuildAndroid="28"
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build android
    - os: osx
      env:
        - BuildiOS="12"
        - Xcode="10"
      osx_image: xcode10
      language: node_js
      node_js: '10'
      jdk: oraclejdk8
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build ios
    - stage: WebPack Core
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode10
      language: node_js
      node_js: '10'
      jdk: oraclejdk8
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
      script: >-
        cd demo && npm run build.plugin && npm i && tns build ios --bundle
        --env.uglify
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 10
      script: >-
        cd demo && npm run build.plugin && npm i && tns build android --bundle
        --env.uglify --env.snapshot
    - stage: Tests
    - os: linux
      language: android
      dist: precise
      jdk: oraclejdk8
      env:
        - Android="UnitTests"
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      before_install:
        - nvm install 8
      script:
        - cd src && npm i && npm run tsc && npm run tslint && cd ../demo && tns build android
        - travis_wait travis_retry tns test android --justlaunch
    - os: osx
      language: node_js
      node_js: '8'
      jdk: oraclejdk8
      env:
        - iOS="UnitTests"
      osx_image: xcode10.0
      script:
        - cd src && npm i && npm run tsc && npm run tslint && cd ../demo && tns build ios
        - travis_wait travis_retry tns test ios --justlaunch

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - android-21
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
